
server:
  port: 8181
  servlet.context-path: /hiauth

logging.level:
  root: @logging.level@
  com.bestaone.aiwan: @logging.level@

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: @hiauth.database.url@
  username: @hiauth.database.username@
  password: @hiauth.database.password@

spring.redis:
    host: @hiauth.redis.host@
    port: @hiauth.redis.port@
    database: @hiauth.redis.database@
    password:

spring.session.store-type: none
spring.devtools.restart.enabled: true

spring.jackson:
  default-property-inclusion: non_null
  serialization.write-dates-as-timestamps: true

# 不配的话，打成jar无法访问页面
spring.thymeleaf:
    cache: true
    prefix: classpath:/templates
    mode: HTML5

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bestaone.hiauth.domain

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  autoRuntimeDialect: true
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: false
  returnPageInfo: true
  params: count=countSql

swagger2.auth:
  clientId: @hiauth.auth.clientId@
  clientSecret: @hiauth.auth.clientSecret@
  authorizationUri: @hiauth.auth.authorizationUri@
  tokenUri: @hiauth.auth.tokenUri@
  scopes: AUTH

hiauth.cacheControl.maxAge : @hiauth.cacheControl.maxAge@